name: Build and Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      # 1. Download the repository code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Install/configure Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # 3. Build the application and run unit tests
      - name: Build and run tests
        run: mvn clean test
